### ISSUE TITLE
Problem: The agent_transfers Data endpoint throws an AttributeError for AIPs with files extracted from a package

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#104]
While refactoring the Data modules for https://github.com/artefactual-labs/AIPscan/pull/98, I discovered that the `agent_transfers` Data endpoint throws an `AttributeError` if an AIP consists exclusively of files extracted from a package that is itself deleted after extraction. At first I thought this was related to my changes, but I'm seeing the same behaviour in the `main` branch.

Traceback:

```
Traceback (most recent call last):
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/twalsh/dev/AIPscan/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/twalsh/dev/AIPscan/AIPscan/API/namespace_data.py", line 176, in get
    return data.agents_transfers(storage_service_id=storage_service_id)
  File "/home/twalsh/dev/AIPscan/AIPscan/Data/data.py", line 466, in agents_transfers
    log_line[FIELD_INGEST_START_DATE] = str(event.date)
AttributeError: 'NoneType' object has no attribute 'date'

```

To replicate, create an AIP with the `SampleTransfers/ISODiskImage` transfer source and default `automated` processing configuration, run a fetch job on that Storage Service from AIPscan, and then try to load the "Transfers log" report or call the related API endpoint for that Storage Service.

It seems that the issue is that files extracted from a package do not have an "ingestion" event, resulting in `event` on line 466 being `None` rather than an `Event` object. We may want to use a different event type in the [event fetching logic](https://github.com/artefactual-labs/AIPscan/blob/39dbf8801e0b52e58f6e3f1cc9f438929849b85e/AIPscan/Data/data.py#L457-L462) within the endpoint, or add handling and logging for when an appropriate event is not available.

**Comment by ross-spencer** [comment]
That's a pain we caught part of this use-case by changing that query. Is there an ingestion event type at all in that METS file? In a normal workflow which extracts files the original zip-like object would have received an Ingestion event. The extracted objects wouldn't.

**Comment by tw4l** [comment]
Hey @ross-spencer - you're right, there are ingestion events in that METS file. This is just a working theory but I think maybe what's happening is that when the processing config is set to delete packages after extraction, there's no file object in the database for those events to be related to when the METS file is being read to the database in the `Aggregator` component, so the ingestion events aren't written to the AIPscan database?

To test this, I used this little SQL script against the AIPscan database, with two AIPs created from the `SampleTransfers/ISODiskImage` test transfer:

- One where the processing config was set to delete packages after extraction (AIP 1)
- One where the processing config was set not to delete packages after extraction (AIP 2)

```
SELECT e.type, f.name from event e
JOIN file f on f.id = e.file_id
WHERE e.type = 'ingestion'
AND f.aip_id = '<AIP ID HERE>';
```

I get a result of `ingestion | images.iso` for AIP 2, but no results for AIP 1.

**Comment by ross-spencer** [comment]
Cripes! Thanks Tessa. That's illuminating. Definitely feels like figuring out what the robust approach for AIPscan. Looking at the [PREMIS dictionary](https://www.loc.gov/standards/premis/v3/preservation-events.pdf) I didn't realize there is a set of Ingestion Start/End events! TIL! That aside, worth us also asking Evelyn and Sarah about AM handling here? I have an instinct about needing to record the ISO in this case (and I guess this would also happen for a transfer with a single zipped file - so I'd do the same there) but it might not be necessary. There might be some analysis around the ISO work to expand on this.

**Comment by tw4l** [comment]
Yeah, this is a tricky one! My gut feeling is that I agree we maybe should have a File entry for the deleted package if possible (with some sort of indication that it was deleted after extraction) but I think getting Evelyn and Sarah's opinions is a good next step.

In the meantime, it might be worth considering adding something like the following? (I'm thinking Peter's error handling work might give us a nice hook for logging the error)

```python3
...
for aip in aips:
    event = (
            db.session.query(Event)
            .join(File)
            .filter(File.aip_id == aip.id, Event.type == EVENT_TYPE)
            .first()
    )
    if event is None:
        # Log error
        continue
    log_line = {}
    ...
```
