### ISSUE TITLE
Archivematica 1.13 / MySQL

### ISSUE THREAD

**Issue by jmcgranahan** [artefactual-labs/AIPscan#166]
We are unable to start the aipscan.service and looking at the logs, it appears it cannot connect to the SQLite DB. But since we upgraded to 1.13.1 just recently, we don't have SQLite. Any plans to update the scripts to look for MySQL?

`Nov 18 13:47:23 libvm01 gunicorn: connection = pool._invoke_creator(self)
Nov 18 13:47:23 libvm01 gunicorn: File "/usr/share/archivematica/virtualenvs/AIPscan/lib64/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
Nov 18 13:47:23 libvm01 gunicorn: return dialect.connect(*cargs, **cparams)
Nov 18 13:47:23 libvm01 gunicorn: File "/usr/share/archivematica/virtualenvs/AIPscan/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 488, in connect
Nov 18 13:47:23 libvm01 gunicorn: return self.dbapi.connect(*cargs, **cparams)
Nov 18 13:47:23 libvm01 gunicorn: sqlite3.OperationalError: unable to open database file
Nov 18 13:47:23 libvm01 gunicorn: The above exception was the direct cause of the following exception:
Nov 18 13:47:23 libvm01 gunicorn: Traceback (most recent call last):
`

**Comment by mcantelon** [comment]
@jmcgranahan Our apologies for overlooking this issue earlier. To be clear are you asking if we're going to support MySQL for data storage in AIPscan? If so, that's not something we're currently looking at, but we might consider in the future. As for the error you're running into it might be a permissions issue (in which case you'd likely need to execute "`sudo chown <AIPscan system user> <path to AIPscan source code directory>`") or you might not have SQLite support installed on your server.
